version: "3.9"

services:
  db:
    image: postgres:16
    container_name: qr_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 3s
      timeout: 3s
      retries: 20

  # Optional: Redis for ActionCable/Hotwire/etc.
  # redis:
  #   image: redis:7
  #   container_name: qr_redis
  #   restart: unless-stopped
  #   ports:
  #     - "6380:6379"

volumes:
  pgdata:
